ALTER TABLE trades ADD COLUMN IF NOT EXISTS is_sample BOOLEAN DEFAULT false;
ALTER TABLE journals ADD COLUMN IF NOT EXISTS is_sample BOOLEAN DEFAULT false;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS is_sample BOOLEAN DEFAULT false;
